spring.cloud.azure.servicebus.namespace=${QUEUE_CONN_STRING}
spring.cloud.azure.servicebus.entity-type=queue
spring.datasource.url=${DB_CONN_STRING}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver